// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TerraSegura.Infrastructure.Context;

#nullable disable

namespace TerraSegura.Migrations
{
    [DbContext(typeof(TerraSeguraContext))]
    partial class TerraSeguraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TerraSegura.Domain.Entity.RegiaoMonitorada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("Id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("Descricao");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("Latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("Longitude");

                    b.Property<string>("NivelRisco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NivelRisco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("RegiaoMonitoradaNET", (string)null);
                });

            modelBuilder.Entity("TerraSegura.Domain.Entity.SensorLeitura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("DataHora");

                    b.Property<Guid>("RegiaoMonitoradaId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TipoSensor");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("RegiaoMonitoradaId");

                    b.ToTable("SensorLeituraNET", (string)null);
                });

            modelBuilder.Entity("TerraSegura.Domain.Entity.SensorLeitura", b =>
                {
                    b.HasOne("TerraSegura.Domain.Entity.RegiaoMonitorada", null)
                        .WithMany("SensoresLeituras")
                        .HasForeignKey("RegiaoMonitoradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TerraSegura.Domain.Entity.RegiaoMonitorada", b =>
                {
                    b.Navigation("SensoresLeituras");
                });
#pragma warning restore 612, 618
        }
    }
}
